Python 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
=============================================== RESTART: C:/Users/ζ/Desktop/Agonia.py ===============================================
card 1 : Queen Clubs
card 2 : 9 Hearts
card 3 : 4 Diamonds
card 4 : 5 Diamonds
card 5 : Jack Clubs
card 6 : 10 Spades
card 7 : Jack Spades
Card on Table: 7 Diamonds
Select card number to play or press enter to draw a card
Card drawn: 2 Spades
Card on Table: 7 Hearts
Card on Table: 10 Hearts
card 1 : Queen Clubs
card 2 : 9 Hearts
card 3 : 4 Diamonds
card 4 : 5 Diamonds
card 5 : Jack Clubs
card 6 : 10 Spades
card 7 : Jack Spades
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 8 Diamonds
card 11 : Ace Hearts
card 12 : 7 Clubs
Card on Table: 10 Hearts
Select card number to play or press enter to draw a card
Card drawn: 3 Hearts
Card on Table: 10 Hearts
Card on Table: Jack Hearts
card 1 : Queen Clubs
card 2 : 9 Hearts
card 3 : 4 Diamonds
card 4 : 5 Diamonds
card 5 : Jack Clubs
card 6 : 10 Spades
card 7 : Jack Spades
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 8 Diamonds
card 11 : Ace Hearts
card 12 : 7 Clubs
card 13 : 3 Hearts
Card on Table: Jack Hearts
Select card number to play or press enter to draw a card
Card drawn: 3 Spades
Card on Table: Jack Hearts
Card on Table: Jack Diamonds
card 1 : Queen Clubs
card 2 : 9 Hearts
card 3 : 4 Diamonds
card 4 : 5 Diamonds
card 5 : Jack Clubs
card 6 : 10 Spades
card 7 : Jack Spades
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 8 Diamonds
card 11 : Ace Hearts
card 12 : 7 Clubs
card 13 : 3 Hearts
card 14 : 3 Spades
Card on Table: Jack Diamonds
Select card number to play or press enter to draw a card
Card drawn: 8 Spades
Card on Table: Jack Diamonds
Card on Table: 6 Diamonds
!!!!!!!!!!!!!!!!!!!!!!!
CPU remaining cards = 2
!!!!!!!!!!!!!!!!!!!!!!!
card 1 : Queen Clubs
card 2 : 9 Hearts
card 3 : 4 Diamonds
card 4 : 5 Diamonds
card 5 : Jack Clubs
card 6 : 10 Spades
card 7 : Jack Spades
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 8 Diamonds
card 11 : Ace Hearts
card 12 : 7 Clubs
card 13 : 3 Hearts
card 14 : 3 Spades
card 15 : 8 Spades
Card on Table: 6 Diamonds
Select card number to play or press enter to draw a card
Card drawn: King Diamonds
Card on Table: 6 Diamonds
Card on Table: 6 Diamonds
card 1 : Queen Clubs
card 2 : 9 Hearts
card 3 : 4 Diamonds
card 4 : 5 Diamonds
card 5 : Jack Clubs
card 6 : 10 Spades
card 7 : Jack Spades
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 8 Diamonds
card 11 : Ace Hearts
card 12 : 7 Clubs
card 13 : 3 Hearts
card 14 : 3 Spades
card 15 : 8 Spades
card 16 : King Diamonds
Card on Table: 6 Diamonds
Select card number to play or press enter to draw a card
Card drawn: King Hearts
Card on Table: 6 Diamonds
Card on Table: 6 Diamonds
card 1 : Queen Clubs
card 2 : 9 Hearts
card 3 : 4 Diamonds
card 4 : 5 Diamonds
card 5 : Jack Clubs
card 6 : 10 Spades
card 7 : Jack Spades
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 8 Diamonds
card 11 : Ace Hearts
card 12 : 7 Clubs
card 13 : 3 Hearts
card 14 : 3 Spades
card 15 : 8 Spades
card 16 : King Diamonds
card 17 : King Hearts
Card on Table: 6 Diamonds
Select card number to play or press enter to draw a card
Card drawn: 3 Diamonds
Card on Table: 6 Diamonds
Card on Table: 6 Diamonds
card 1 : Queen Clubs
card 2 : 9 Hearts
card 3 : 4 Diamonds
card 4 : 5 Diamonds
card 5 : Jack Clubs
card 6 : 10 Spades
card 7 : Jack Spades
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 8 Diamonds
card 11 : Ace Hearts
card 12 : 7 Clubs
card 13 : 3 Hearts
card 14 : 3 Spades
card 15 : 8 Spades
card 16 : King Diamonds
card 17 : King Hearts
card 18 : 3 Diamonds
Card on Table: 6 Diamonds
Select card number to play or press enter to draw a card
Card drawn: Ace Diamonds
Card on Table: 6 Diamonds
Card on Table: Queen Diamonds
card 1 : Queen Clubs
card 2 : 9 Hearts
card 3 : 4 Diamonds
card 4 : 5 Diamonds
card 5 : Jack Clubs
card 6 : 10 Spades
card 7 : Jack Spades
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 8 Diamonds
card 11 : Ace Hearts
card 12 : 7 Clubs
card 13 : 3 Hearts
card 14 : 3 Spades
card 15 : 8 Spades
card 16 : King Diamonds
card 17 : King Hearts
card 18 : 3 Diamonds
card 19 : Ace Diamonds
Card on Table: Queen Diamonds
Select card number to play or press enter to draw a card
Card drawn: 6 Hearts
Card on Table: Queen Diamonds
Card on Table: Queen Spades
card 1 : Queen Clubs
card 2 : 9 Hearts
card 3 : 4 Diamonds
card 4 : 5 Diamonds
card 5 : Jack Clubs
card 6 : 10 Spades
card 7 : Jack Spades
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 8 Diamonds
card 11 : Ace Hearts
card 12 : 7 Clubs
card 13 : 3 Hearts
card 14 : 3 Spades
card 15 : 8 Spades
card 16 : King Diamonds
card 17 : King Hearts
card 18 : 3 Diamonds
card 19 : Ace Diamonds
card 20 : 6 Hearts
Card on Table: Queen Spades
Select card number to play or press enter to draw a card
Card drawn: Ace Clubs
Card on Table: Queen Spades
Card on Table: 4 Spades
!!!!!!!!!!!!!!!!!!!!!!!
CPU remaining cards = 2
!!!!!!!!!!!!!!!!!!!!!!!
card 1 : Queen Clubs
card 2 : 9 Hearts
card 3 : 4 Diamonds
card 4 : 5 Diamonds
card 5 : Jack Clubs
card 6 : 10 Spades
card 7 : Jack Spades
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 8 Diamonds
card 11 : Ace Hearts
card 12 : 7 Clubs
card 13 : 3 Hearts
card 14 : 3 Spades
card 15 : 8 Spades
card 16 : King Diamonds
card 17 : King Hearts
card 18 : 3 Diamonds
card 19 : Ace Diamonds
card 20 : 6 Hearts
card 21 : Ace Clubs
Card on Table: 4 Spades
Select card number to play or press enter to draw a card
Card drawn: 6 Clubs
Card on Table: 4 Spades
Card on Table: 4 Spades
card 1 : Queen Clubs
card 2 : 9 Hearts
card 3 : 4 Diamonds
card 4 : 5 Diamonds
card 5 : Jack Clubs
card 6 : 10 Spades
card 7 : Jack Spades
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 8 Diamonds
card 11 : Ace Hearts
card 12 : 7 Clubs
card 13 : 3 Hearts
card 14 : 3 Spades
card 15 : 8 Spades
card 16 : King Diamonds
card 17 : King Hearts
card 18 : 3 Diamonds
card 19 : Ace Diamonds
card 20 : 6 Hearts
card 21 : Ace Clubs
card 22 : 6 Clubs
Card on Table: 4 Spades
Select card number to play or press enter to draw a card
Card drawn: 9 Clubs
Card on Table: 4 Spades
Card on Table: 4 Clubs
!!!!!!!!!!!!!!!!!!!!!!!
CPU remaining cards = 2
!!!!!!!!!!!!!!!!!!!!!!!
card 1 : Queen Clubs
card 2 : 9 Hearts
card 3 : 4 Diamonds
card 4 : 5 Diamonds
card 5 : Jack Clubs
card 6 : 10 Spades
card 7 : Jack Spades
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 8 Diamonds
card 11 : Ace Hearts
card 12 : 7 Clubs
card 13 : 3 Hearts
card 14 : 3 Spades
card 15 : 8 Spades
card 16 : King Diamonds
card 17 : King Hearts
card 18 : 3 Diamonds
card 19 : Ace Diamonds
card 20 : 6 Hearts
card 21 : Ace Clubs
card 22 : 6 Clubs
card 23 : 9 Clubs
Card on Table: 4 Clubs
Select card number to play or press enter to draw a card
Card drawn: 3 Clubs
Card on Table: 4 Clubs
Card on Table: 10 Clubs
!!!!!!!!!!!!!!!!!!!!!!!
CPU remaining cards = 1
!!!!!!!!!!!!!!!!!!!!!!!
card 1 : Queen Clubs
card 2 : 9 Hearts
card 3 : 4 Diamonds
card 4 : 5 Diamonds
card 5 : Jack Clubs
card 6 : 10 Spades
card 7 : Jack Spades
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 8 Diamonds
card 11 : Ace Hearts
card 12 : 7 Clubs
card 13 : 3 Hearts
card 14 : 3 Spades
card 15 : 8 Spades
card 16 : King Diamonds
card 17 : King Hearts
card 18 : 3 Diamonds
card 19 : Ace Diamonds
card 20 : 6 Hearts
card 21 : Ace Clubs
card 22 : 6 Clubs
card 23 : 9 Clubs
card 24 : 3 Clubs
Card on Table: 10 Clubs
Select card number to play or press enter to draw a card
Card drawn: 8 Hearts
Card on Table: 10 Clubs
Card on Table: 5 Clubs
CPU Wins ...
>>> 
=============================================== RESTART: C:/Users/ζ/Desktop/Agonia.py ===============================================
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
Card on Table: 2 Diamonds
Select card number to play or press enter to draw a card
Card drawn: 4 Hearts
Card on Table: 2 Diamonds
Card on Table: Ace Clubs
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
Card on Table: Ace Clubs
Select card number to play or press enter to draw a card
Card drawn: 10 Spades
press 1:Clubs,2:Diamonds,3:Hearts,4:Spades1
Card on Table: Ace Clubs
Card on Table: 6 Clubs
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
Card on Table: 6 Clubs
Select card number to play or press enter to draw a card
Card drawn: 6 Diamonds
Card on Table: 6 Clubs
Card on Table: 6 Spades
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
Card on Table: 6 Spades
Select card number to play or press enter to draw a card
Card drawn: Jack Clubs
Card on Table: 6 Spades
Card on Table: Ace Spades
!!!!!!!!!!!!!!!!!!!!!!!
CPU remaining cards = 2
!!!!!!!!!!!!!!!!!!!!!!!
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
card 11 : Jack Clubs
Card on Table: Ace Spades
Select card number to play or press enter to draw a card
Card drawn: Jack Hearts
Card on Table: Ace Spades
Card on Table: Ace Spades
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
card 11 : Jack Clubs
card 12 : Jack Hearts
Card on Table: Ace Spades
Select card number to play or press enter to draw a card
Card drawn: Queen Spades
Card on Table: Ace Spades
Card on Table: Ace Spades
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
card 11 : Jack Clubs
card 12 : Jack Hearts
card 13 : Queen Spades
Card on Table: Ace Spades
Select card number to play or press enter to draw a card
Card drawn: 2 Spades
Card on Table: Ace Spades
Card on Table: Ace Spades
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
card 11 : Jack Clubs
card 12 : Jack Hearts
card 13 : Queen Spades
card 14 : 2 Spades
Card on Table: Ace Spades
Select card number to play or press enter to draw a card
Card drawn: 2 Clubs
Card on Table: Ace Spades
Card on Table: Ace Spades
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
card 11 : Jack Clubs
card 12 : Jack Hearts
card 13 : Queen Spades
card 14 : 2 Spades
card 15 : 2 Clubs
Card on Table: Ace Spades
Select card number to play or press enter to draw a card
Card drawn: 10 Diamonds
Card on Table: Ace Spades
Card on Table: Ace Spades
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
card 11 : Jack Clubs
card 12 : Jack Hearts
card 13 : Queen Spades
card 14 : 2 Spades
card 15 : 2 Clubs
card 16 : 10 Diamonds
Card on Table: Ace Spades
Select card number to play or press enter to draw a card
Card drawn: 4 Diamonds
Card on Table: Ace Spades
Card on Table: Ace Hearts
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
card 11 : Jack Clubs
card 12 : Jack Hearts
card 13 : Queen Spades
card 14 : 2 Spades
card 15 : 2 Clubs
card 16 : 10 Diamonds
card 17 : 4 Diamonds
Card on Table: Ace Hearts
Select card number to play or press enter to draw a card
Card drawn: 8 Hearts
press 1:Clubs,2:Diamonds,3:Hearts,4:Spades1
Card on Table: Ace Clubs
Card on Table: 4 Clubs
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
card 11 : Jack Clubs
card 12 : Jack Hearts
card 13 : Queen Spades
card 14 : 2 Spades
card 15 : 2 Clubs
card 16 : 10 Diamonds
card 17 : 4 Diamonds
card 18 : 8 Hearts
Card on Table: 4 Clubs
Select card number to play or press enter to draw a card
Card drawn: 7 Hearts
Card on Table: 4 Clubs
Card on Table: 4 Clubs
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
card 11 : Jack Clubs
card 12 : Jack Hearts
card 13 : Queen Spades
card 14 : 2 Spades
card 15 : 2 Clubs
card 16 : 10 Diamonds
card 17 : 4 Diamonds
card 18 : 8 Hearts
card 19 : 7 Hearts
Card on Table: 4 Clubs
Select card number to play or press enter to draw a card
Card drawn: 9 Clubs
Card on Table: 4 Clubs
Card on Table: 4 Clubs
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
card 11 : Jack Clubs
card 12 : Jack Hearts
card 13 : Queen Spades
card 14 : 2 Spades
card 15 : 2 Clubs
card 16 : 10 Diamonds
card 17 : 4 Diamonds
card 18 : 8 Hearts
card 19 : 7 Hearts
card 20 : 9 Clubs
Card on Table: 4 Clubs
Select card number to play or press enter to draw a card
Card drawn: 8 Spades
Card on Table: 4 Clubs
Card on Table: King Clubs
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
card 11 : Jack Clubs
card 12 : Jack Hearts
card 13 : Queen Spades
card 14 : 2 Spades
card 15 : 2 Clubs
card 16 : 10 Diamonds
card 17 : 4 Diamonds
card 18 : 8 Hearts
card 19 : 7 Hearts
card 20 : 9 Clubs
card 21 : 8 Spades
Card on Table: King Clubs
Select card number to play or press enter to draw a card
Card drawn: Jack Diamonds
Card on Table: King Clubs
Card on Table: King Diamonds
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
card 11 : Jack Clubs
card 12 : Jack Hearts
card 13 : Queen Spades
card 14 : 2 Spades
card 15 : 2 Clubs
card 16 : 10 Diamonds
card 17 : 4 Diamonds
card 18 : 8 Hearts
card 19 : 7 Hearts
card 20 : 9 Clubs
card 21 : 8 Spades
card 22 : Jack Diamonds
Card on Table: King Diamonds
Select card number to play or press enter to draw a card
Card drawn: 4 Spades
Card on Table: King Diamonds
Card on Table: Queen Diamonds
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
card 11 : Jack Clubs
card 12 : Jack Hearts
card 13 : Queen Spades
card 14 : 2 Spades
card 15 : 2 Clubs
card 16 : 10 Diamonds
card 17 : 4 Diamonds
card 18 : 8 Hearts
card 19 : 7 Hearts
card 20 : 9 Clubs
card 21 : 8 Spades
card 22 : Jack Diamonds
card 23 : 4 Spades
Card on Table: Queen Diamonds
Select card number to play or press enter to draw a card
Card drawn: 7 Spades
Card on Table: Queen Diamonds
Card on Table: 5 Diamonds
card 1 : 2 Hearts
card 2 : 7 Diamonds
card 3 : Ace Diamonds
card 4 : 3 Diamonds
card 5 : 10 Clubs
card 6 : King Spades
card 7 : Queen Clubs
card 8 : 4 Hearts
card 9 : 10 Spades
card 10 : 6 Diamonds
card 11 : Jack Clubs
card 12 : Jack Hearts
card 13 : Queen Spades
card 14 : 2 Spades
card 15 : 2 Clubs
card 16 : 10 Diamonds
card 17 : 4 Diamonds
card 18 : 8 Hearts
card 19 : 7 Hearts
card 20 : 9 Clubs
card 21 : 8 Spades
card 22 : Jack Diamonds
card 23 : 4 Spades
card 24 : 7 Spades
Card on Table: 5 Diamonds
Select card number to play or press enter to draw a card
Card drawn: 3 Spades
Card on Table: 5 Diamonds
Card on Table: 5 Diamonds
Traceback (most recent call last):
  File "C:/Users/ζ/Desktop/Agonia.py", line 353, in <module>
    deck.remove(tempdeck(i))
TypeError: 'list' object is not callable
>>> 
=============================================== RESTART: C:/Users/ζ/Desktop/Agonia.py ===============================================
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 2 Spades
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 2 Hearts
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 7 Hearts
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 9 Spades
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: King Clubs
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: Queen Spades
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 5 Spades
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 4 Hearts
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 6 Hearts
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 9 Diamonds
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 5 Diamonds
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 8 Spades
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 10 Spades
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: Jack Diamonds
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 4 Diamonds
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 3 Hearts
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: Ace Hearts
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 4 Spades
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 4 Clubs
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 10 Diamonds
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 10 Clubs
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: Ace Diamonds
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 7 Clubs
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: Jack Clubs
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 9 Hearts
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 6 Diamonds
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 3 Clubs
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: King Spades
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: Queen Hearts
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 8 Diamonds
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: Queen Diamonds
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 2 Clubs
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: King Hearts
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 7 Diamonds
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: Ace Spades
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
card 42 : Ace Spades
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 6 Spades
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
card 42 : Ace Spades
card 43 : 6 Spades
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 8 Clubs
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
card 42 : Ace Spades
card 43 : 6 Spades
card 44 : 8 Clubs
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 5 Clubs
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
card 42 : Ace Spades
card 43 : 6 Spades
card 44 : 8 Clubs
card 45 : 5 Clubs
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 3 Spades
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
card 42 : Ace Spades
card 43 : 6 Spades
card 44 : 8 Clubs
card 45 : 5 Clubs
card 46 : 3 Spades
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: Jack Spades
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
card 42 : Ace Spades
card 43 : 6 Spades
card 44 : 8 Clubs
card 45 : 5 Clubs
card 46 : 3 Spades
card 47 : Jack Spades
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: Jack Hearts
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
card 42 : Ace Spades
card 43 : 6 Spades
card 44 : 8 Clubs
card 45 : 5 Clubs
card 46 : 3 Spades
card 47 : Jack Spades
card 48 : Jack Hearts
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 6 Clubs
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
card 42 : Ace Spades
card 43 : 6 Spades
card 44 : 8 Clubs
card 45 : 5 Clubs
card 46 : 3 Spades
card 47 : Jack Spades
card 48 : Jack Hearts
card 49 : 6 Clubs
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: Queen Clubs
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
card 42 : Ace Spades
card 43 : 6 Spades
card 44 : 8 Clubs
card 45 : 5 Clubs
card 46 : 3 Spades
card 47 : Jack Spades
card 48 : Jack Hearts
card 49 : 6 Clubs
card 50 : Queen Clubs
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 2 Diamonds
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
card 42 : Ace Spades
card 43 : 6 Spades
card 44 : 8 Clubs
card 45 : 5 Clubs
card 46 : 3 Spades
card 47 : Jack Spades
card 48 : Jack Hearts
card 49 : 6 Clubs
card 50 : Queen Clubs
card 51 : 2 Diamonds
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 7 Spades
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
card 42 : Ace Spades
card 43 : 6 Spades
card 44 : 8 Clubs
card 45 : 5 Clubs
card 46 : 3 Spades
card 47 : Jack Spades
card 48 : Jack Hearts
card 49 : 6 Clubs
card 50 : Queen Clubs
card 51 : 2 Diamonds
card 52 : 7 Spades
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: King Diamonds
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
card 42 : Ace Spades
card 43 : 6 Spades
card 44 : 8 Clubs
card 45 : 5 Clubs
card 46 : 3 Spades
card 47 : Jack Spades
card 48 : Jack Hearts
card 49 : 6 Clubs
card 50 : Queen Clubs
card 51 : 2 Diamonds
card 52 : 7 Spades
card 53 : King Diamonds
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: 10 Hearts
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
card 42 : Ace Spades
card 43 : 6 Spades
card 44 : 8 Clubs
card 45 : 5 Clubs
card 46 : 3 Spades
card 47 : Jack Spades
card 48 : Jack Hearts
card 49 : 6 Clubs
card 50 : Queen Clubs
card 51 : 2 Diamonds
card 52 : 7 Spades
card 53 : King Diamonds
card 54 : 10 Hearts
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card
Card drawn: Ace Clubs
card 1 : 5 Clubs
card 2 : 3 Spades
card 3 : 6 Clubs
card 4 : Queen Clubs
card 5 : 2 Diamonds
card 6 : Ace Clubs
card 7 : 8 Hearts
card 8 : 2 Spades
card 9 : 2 Hearts
card 10 : 7 Hearts
card 11 : 9 Spades
card 12 : King Clubs
card 13 : Queen Spades
card 14 : 5 Spades
card 15 : 4 Hearts
card 16 : 6 Hearts
card 17 : 9 Diamonds
card 18 : 5 Diamonds
card 19 : 8 Spades
card 20 : 10 Spades
card 21 : Jack Diamonds
card 22 : 4 Diamonds
card 23 : 3 Hearts
card 24 : Ace Hearts
card 25 : 4 Spades
card 26 : 4 Clubs
card 27 : 10 Diamonds
card 28 : 10 Clubs
card 29 : Ace Diamonds
card 30 : 7 Clubs
card 31 : Jack Clubs
card 32 : 9 Hearts
card 33 : 6 Diamonds
card 34 : 3 Clubs
card 35 : King Spades
card 36 : Queen Hearts
card 37 : 8 Diamonds
card 38 : Queen Diamonds
card 39 : 2 Clubs
card 40 : King Hearts
card 41 : 7 Diamonds
card 42 : Ace Spades
card 43 : 6 Spades
card 44 : 8 Clubs
card 45 : 5 Clubs
card 46 : 3 Spades
card 47 : Jack Spades
card 48 : Jack Hearts
card 49 : 6 Clubs
card 50 : Queen Clubs
card 51 : 2 Diamonds
card 52 : 7 Spades
card 53 : King Diamonds
card 54 : 10 Hearts
card 55 : Ace Clubs
Card on Table: 9 Clubs
Select card number to play or press enter to draw a card